changed the way docker-services are installed

diff --git a/run_once_50-install-podman-systemd-units.sh.tmpl b/run_once_50-install-podman-systemd-units.sh.tmpl
--- a/run_once_50-install-podman-systemd-units.sh.tmpl
+++ b/run_once_50-install-podman-systemd-units.sh.tmpl
@@ -1,8 +1,55 @@
 #!/usr/bin/env bash
+{{ if (eq .chezmoi.hostname "kvineet-pc") -}}
+if (! command -v podman-compose > /dev/null) || (! command -v podman > /dev/null); then
+    echo "podman and podman-compose required..."
+    exit 1
+fi
+echo "generating podman config..."
+# For each  service
+#  - start pod using podman-compose
+#  - generate systemd units
+{{ if (has "emby" .podman ) -}}
+if ! sudo podman pod exists emby; then
+    sudo podman-compose -f {{ joinPath .chezmoi.sourceDir "etc/docker-services/emby/docker-compose.yaml" | quote }} up -d
+fi
+sudo podman generate systemd --files --name emby
+{{ end -}}
+{{ if (has "torrent" .podman) }}
+if ! sudo podman pod exists torrent; then
+sudo podman-compose -f {{ joinPath .chezmoi.sourceDir "etc/docker-services/torrent/docker-compose.yaml" | quote }} up -d
+fi
+sudo podman generate systemd --files --name torrent
+{{ end -}}
+{{ if (has "plex" .podman) }}
+if ! sudo podman pod exists plex; then
+sudo podman-compose -f {{ joinPath .chezmoi.sourceDir "etc/docker-services/plex/docker-compose.yaml" | quote }} up -d
+fi
+sudo podman generate systemd --files --name plex
+{{ end -}}
+{{ if (has "webDav" .podman) }}
+if ! sudo podman pod exists webdav; then
+sudo podman-compose -f {{ joinPath .chezmoi.sourceDir "etc/docker-services/webdav/docker-compose.yaml" | quote }} up -d
+fi
+sudo podman generate systemd --files --name webdav
+{{ end -}}
 
 # Copy service files to systemd units folder
-sudo cp {{ joinPath .chezmoi.sourceDir "etc/systemd" | quote }}/*.service /etc/systemd/system/
+sudo mv *.service /etc/systemd/system/
 # Reload daemon to load new unit files
 systemctl daemon-reload
 # enable services
-systemctl enable pod-emby pod-torrent
+{{ if (has "emby" .podman ) -}}
+systemctl enable pod-emby
+{{ end -}}
+{{ if (has "torrent" .podman ) -}}
+systemctl enable pod-torrent
+{{ end -}}
+{{ if (has "plex" .podman ) -}}
+systemctl enable pod-plex
+{{ end -}}
+{{ if (has "webDav" .podman ) -}}
+systemctl enable pod-webDav
+{{ end -}}
+
+{{ end -}}
+#  LocalWords:  webDav
